<a href="https://colab.research.google.com/github/mdsiam135/thesis_2025/blob/main/Categorical_to_Numerical.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
path = "/content/drive/MyDrive/UpdatedDataset/Dataset(2014-2024).csv"
df = pd.read_csv(path , encoding='ISO-8859-1')
df.head(11)

,Crop,District,Area (Acres),Production (M.Ton),Year,Temperature at 2 Meters Range (C),Precipitation Corrected (mm),Root Zone Soil Wetness (surface to 100 cm below),Surface Soil Wetness (surface to 5 cm below),relative_humidity_2m(%),soil_temperature_0_to_7cm(C),soil_moiture_7_to_28cm(m³/m³),soil_moisture_0_to_7cm(m³/m³),total_rain_mm
0,Onion,Barguna,80.0,62.0,2014,24.24,6.92,0.78,0.74,78.35049,27.33195,0.377319,0.331680,1425.7
1,Onion,Barguna,108.0,127.0,2015,19.86,16.53,0.82,0.80,80.52057,26.84322,0.387514,0.353195,2106.7
2,Onion,Barguna,108.0,124.0,2016,19.68,20.22,0.85,0.85,81.73871,27.31757,0.394643,0.351402,1981.5
3,Onion,Barguna,106.0,124.0,2017,19.69,24.79,0.89,0.89,81.98142,26.88720,0.420786,0.374936,2762.6
4,Onion,Barguna,108.0,128.0,2018,20.39,21.01,0.87,0.86,80.77635,26.67200,0.396435,0.351338,1975.8
5,Onion,Barguna,108.0,128.0,2019,18.77,25.73,0.89,0.89,80.56498,26.87627,0.404664,0.356340,1579.9
6,Onion,Barguna,109.0,158.0,2020,20.02,19.60,0.89,0.89,82.33088,26.38537,0.417089,0.369976,2212.9
7,Onion,Barguna,104.0,124.0,2021,21.85,15.66,0.84,0.83,80.74391,27.08039,0.392532,0.349823,2723.7
8,Onion,Barguna,100.0,117.0,2022,19.85,11.50,0.86,0.85,79.29090,26.82983,0.387037,0.342713,1941.5
9,Onion,Barguna,54.0,62.0,2023,21.22,12.92,0.86,0.86,80.35379,27.18543,0.397186,0.351515,2031.0
10,Onion,Barguna,51.0,51.0,2024,25.78,11.17,0.85,0.81,80.17900,26.96220,0.401211,0.356647,2458.3

In [ ]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

# Load the dataset
file_path = "/content/drive/MyDrive/UpdatedDataset/Dataset(2014-2024).csv"
df = pd.read_csv(file_path, encoding='ISO-8859-1')

# ----- Encode 'Crop' -----
crop_encoder = OneHotEncoder(sparse_output=False, drop=None)
crop_encoded = crop_encoder.fit_transform(df[['Crop']])
crop_encoded_df = pd.DataFrame(crop_encoded, columns=crop_encoder.get_feature_names_out(['Crop']))

# ----- Encode 'District' -----
district_encoder = OneHotEncoder(sparse_output=False, drop=None)
district_encoded = district_encoder.fit_transform(df[['District']])
district_encoded_df = pd.DataFrame(district_encoded, columns=district_encoder.get_feature_names_out(['District']))

# Combine all parts: drop original columns and concatenate new encoded ones
df_encoded = pd.concat([df.drop(columns=['Crop', 'District']), crop_encoded_df, district_encoded_df], axis=1)

# Show result
print(df_encoded.head())

   Area (Acres)  Production (M.Ton)  Year  Temperature at 2 Meters Range (C)  \
0          80.0                62.0  2014                              24.24
1         108.0               127.0  2015                              19.86
2         108.0               124.0  2016                              19.68
3         106.0               124.0  2017                              19.69
4         108.0               128.0  2018                              20.39

   Precipitation Corrected (mm)  \
0                          6.92
1                         16.53
2                         20.22
3                         24.79
4                         21.01

   Root Zone Soil Wetness (surface to 100 cm below)  \
0                                              0.78
1                                              0.82
2                                              0.85
3                                              0.89
4                                              0.87

   Surface Soil Wetness (surface to 5 cm below)  relative_humidity_2m(%)  \
0                                          0.74                 78.35049
1                                          0.80                 80.52057
2                                          0.85                 81.73871
3                                          0.89                 81.98142
4                                          0.86                 80.77635

   soil_temperature_0_to_7cm(C)  soil_moiture_7_to_28cm(m³/m³)  ...  \
0                      27.33195                       0.377319  ...
1                      26.84322                       0.387514  ...
2                      27.31757                       0.394643  ...
3                      26.88720                       0.420786  ...
4                      26.67200                       0.396435  ...

   District_Rangamati  District_Rangpur  District_Satkhira  \
0                 0.0               0.0                0.0
1                 0.0               0.0                0.0
2                 0.0               0.0                0.0
3                 0.0               0.0                0.0
4                 0.0               0.0                0.0

   District_Shariatpur  District_Sherpur  District_Sirajganj  \
0                  0.0               0.0                 0.0
1                  0.0               0.0                 0.0
2                  0.0               0.0                 0.0
3                  0.0               0.0                 0.0
4                  0.0               0.0                 0.0

   District_Sunamganj  District_Sylhet  District_Tangail  District_Thakurgaon
0                 0.0              0.0               0.0                  0.0
1                 0.0              0.0               0.0                  0.0
2                 0.0              0.0               0.0                  0.0
3                 0.0              0.0               0.0                  0.0
4                 0.0              0.0               0.0                  0.0

[5 rows x 84 columns]

In [ ]:
# Save the encoded DataFrame to a CSV file
output_path = "all_data_encoded.csv"
df_encoded.to_csv(output_path, index=False)

print(f"✅ Encoded dataset saved to: {output_path}")

✅ Encoded dataset saved to: all_data_encoded.csv

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).